### ISSUE TITLE
Geo location search

### ISSUE THREAD

**Issue by sideroad** [sideroad/express-restful-api#25]
Add `latlng` to attribute type. format is `latitude,longitude`.

Be able to fetch collection filtered by `latitude,longitude,radius(m)`.
Here is a example to search Kyoto around 1km.
`location=35.5783703,136.6170494,1000`

**Comment by toantd90** [comment]
We need to define a GeoJSON Point as below
```
address: {
  type: {
    type: String,
    enum: ['Point'],
    required: true
  },
  coordinates: {
    type: [Number],
    required: true
  }
}
```
But `express-restful-api` only supports five attribute types such as number, boolean, date, array, string.  If I define `address` like above code, current system will be treat `address` as a String.

```
_.each(attrs, (attr, name) => {
  const type = attr.type === 'number'
    ? Number
    : attr.type === 'boolean'
      ? Boolean
      : attr.type === 'date'
        ? Date
        : attr.type === 'children'
          ? Array
          : String;
```

@sideroad Could you please give me a suggestion for this?

**Comment by sideroad** [comment]
As I put the comment above, I planned to add Add "latlng". But I'm agree with to use 'geometry' instead.
